steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build docker package'
    args:
      [
        'build',
        '-t',
        '${_ARTIFACT_REGISTRY_URL}/backend:${COMMIT_SHA}',
        './backend'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker push'
    args:
      [
        'push',
        '${_ARTIFACT_REGISTRY_URL}/backend:${COMMIT_SHA}'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy to cloud run'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'backend',
        '--image',
        '${_ARTIFACT_REGISTRY_URL}/backend:${COMMIT_SHA}',
        '--region',
        'europe-west3',
        '--platform',
        'managed',
        '--set-env-vars',
        'PROJECT_NUMBER=${PROJECT_NUMBER},PROJECT_ID=${_PROJECT_ID},GCP__Location=europe-west3,GCP__TextModelName=text-embedding-005,Jwt__Issuer=waylay-backend,Jwt__Audience=waylay-frontend',
        '--allow-unauthenticated',
        '--set-secrets',
        'Jwt__Key=jwt_key:latest,ConnectionStrings__GcpPostgresConnection=db_connection_string:latest',
        '--add-cloudsql-instances',
        'coba-studteam-1-waylay:europe-west3:waylay-db'
      ]

images:
  - '${_ARTIFACT_REGISTRY_URL}/backend:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
